language: ruby

sudo: false
rvm:
  - 2.3.0
cache:
  bundler

env:
  matrix:
    - EMACS_VERSION=24.4
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.1

before_install:
  - export PATH="$HOME/bin:$PATH"

script:
  - make install_emacs
  - make compile
